### ISSUE TITLE
Date formatting does not appear to support milliseconds or timezone offsets

### ISSUE THREAD

**Issue by rander1870** [thorn0/sffjs#2]
I was unit testing to ensure that all our needs could be supported with this library,  but I was finding that support for formatting dates with milliseconds or timezone offsets did not work as it does in c#.

For example, I had the following unit test code:;

let x = new Date();
console.log(String.format("{0:MM/dd/yyyy hh:mm:ss.fffzzz tt}", x));
console.log(x.format("MM/dd/yyyy hh:mm:ss.fffzzz tt"))
console.log(String.format("{0:MMM zzz}", x));

And for each message displayed, the "zzz" or "fff" was displayed, not the date component.

Is there something syntactically that I am doing wrong?

Thanks

**Comment by thorn0** [comment]
Fixed in v1.13.2.
