### ISSUE TITLE
de-ch shoul contain 'CHF' for curreny

### ISSUE THREAD

**Issue by frankiDotNet** [thorn0/sffjs#3]
Hello,

based on your templates the currency for de-CH should be 'CHF'.

**Comment by thorn0** [comment]
Please submit a pull request.

**Comment by thorn0** [comment]
Also, currency symbol is not the same thing as currency code: $ vs USD, ₺ vs TRY, zł vs PLN, etc.

Is it okay to use 'CHF' as a currency symbol or is probably 'Fr' better?

**Comment by frankiDotNet** [comment]
Tested it on .Net fiddle, the following output for .NET is 'CHF':

```
RegionInfo myRI1 = new RegionInfo( "de-CH" );
Console.WriteLine(myRI1.CurrencySymbol);
CultureInfo myCI = new CultureInfo("de-CH", false);
Console.WriteLine(myCI.NumberFormat.CurrencySymbol);
```
